[runtime]
log_level = "INFO"
dlthub_telemetry = true

[sources.filesystem]
bucket_url = "s3://aws-glue-billing-finance-dev"
file_glob = "2025/07/17/*"
requester_pays = true

[destination.filesystem]
bucket_url = "gs://daneshp-sandbox-delphi-data"
prefix = "2025/07/17/"
