TABLE_SCHEMAS = {
    "action_history": {
        "achi_id": "STRING",
        "empl_id": "STRING",
        "source_name": "STRING",
        "source_ref": "STRING",
        "source_field": "STRING",
        "old_value": "STRING",
        "new_value": "STRING",
        "actp_code": "STRING",
        "related_cove_id": "STRING",
        "related_offer_id": "STRING",
        "related_appl_id": "STRING",
        "comment": "STRING",
        "inserted_by": "STRING",
        "inserted_dtime": "TIMESTAMP",
        "channel_code": "STRING",
        "solvency_level_code": "STRING",
        "reason_code": "STRING",
        "updated_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "application": {
        "appl_id": "STRING",
        "pers_id": "STRING",
        "loty_code": "STRING",
        "status_code": "STRING",
        "status_code_reason": "STRING",
        "amt": "DECIMAL(38, 18)",
        "ccy": "STRING",
        "purpose": "STRING",
        "application_date": "DATE",
        "payment_day": "DECIMAL(38, 18)",
        "monthly_repayment_amt": "DECIMAL(38, 18)",
        "channel_code": "STRING",
        "application_score": "DECIMAL(38, 18)",
        "application_score_due_date": "DATE",
        "interest_rate": "DECIMAL(38, 18)",
        "max_amount": "DECIMAL(38, 18)",
        "source_name": "STRING",
        "source_ref": "STRING",
        "payment_free_months": "ARRAY<STRING>",
        "last_change_date": "DATE",
        "updated_dtime": "TIMESTAMP",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
        "max_invoice_amt": "DECIMAL(38, 18)",
        "min_invoice_amt": "DECIMAL(38, 18)",
        "monthly_repayment_rate": "DECIMAL(38, 18)",
    },
    "borrower": {
        "borr_id": "STRING",
        "pers_id": "STRING",
        "boty_code": "STRING",
        "source_name": "STRING",
        "source_ref": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "cash": {
        "contract_id": "STRING",
        "cash_id": "STRING",
        "reporting_banking_date": "DATE",
        "receivable_event_type_code": "STRING",
        "ccy": "STRING",
        "amt": "DECIMAL(38, 18)",
        "balance_amt": "DECIMAL(38, 18)",
        "posting_date": "DATE",
        "value_date": "DATE",
        "tenant_code": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "contract": {
        "cohe_id": "STRING",
        "contract_number": "STRING",
        "cove_id": "STRING",
        "version_number": "INT32",
        "pers_id": "STRING",
        "loty_code": "STRING",
        "logr_code": "STRING",
        "country_code": "STRING",
        "status_code": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "reports_id": "STRING",
        "reporting_banking_date": "DATE",
        "tenant_code": "STRING",
        "activation_date": "DATE",
        "limit_amt": "DECIMAL(38, 18)",
        "payment_free_months": "ARRAY<STRING>",
        "next_invoice_due_date": "DATE",
        "monthly_repayment_amt": "DECIMAL(38, 18)",
        "ccy": "STRING",
        "number_of_payments": "INT32",
        "apr": "DECIMAL(38, 18)",
        "invoice_delivery_method": "STRING",
        "reference_number": "STRING",
        "message_dtime": "TIMESTAMP",
        "max_invoice_amt": "DECIMAL(38, 18)",
        "min_invoice_amt": "DECIMAL(38, 18)",
        "monthly_repayment_rate": "DECIMAL(38, 18)",
        "actual_closing_date": "DATE",
        "payment_interval": "INT32",
        "umbrella_cohe_id": "STRING",
        "contract_amt": "DECIMAL(38, 18)",
    },
    "contract_condition": {
        "coco_id": "STRING",
        "cohe_id": "STRING",
        "cove_id": "STRING",
        "condition_type_code": "STRING",
        "amt": "DECIMAL(38, 18)",
        "ccy": "STRING",
        "validity_range": "STRING",
        "source_name": "STRING",
        "source_ref": "STRING",
        "reporting_banking_date": "DATE",
        "updated_dtime": "TIMESTAMP",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "custom_field_value": {
        "entity_name": "STRING",
        "entity_ref": "STRING",
        "field_set_id": "STRING",
        "field_id": "STRING",
        "reporting_banking_date": "DATE",
        "value_type": "STRING",
        "value_number": "DECIMAL(38, 18)",
        "value_text": "STRING",
        "value_date": "DATE",
        "value_datetime": "TIMESTAMP",
        "value_boolean": "BOOL",
        "value_json": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "inserted_by": "STRING",
        "inserted_dtime": "TIMESTAMP",
        "updated_by": "STRING",
        "message_dtime": "TIMESTAMP",
        "value_text_array": "ARRAY<STRING>",
    },
    "event": {
        "even_id": "STRING",
        "cohe_id": "STRING",
        "cove_id": "STRING",
        "reporting_banking_date": "DATE",
        "coty_code": "STRING",
        "evty_code": "STRING",
        "posting_date": "DATE",
        "value_date": "DATE",
        "init_balance_amt": "DECIMAL(38, 18)",
        "init_debt_amt": "DECIMAL(38, 18)",
        "balance_dir_code": "STRING",
        "debt_dir_code": "STRING",
        "amt": "DECIMAL(38, 18)",
        "ccy": "STRING",
        "details": "STRING",
        "source_name": "STRING",
        "source_ref": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "event_type": {
        "evty_code": "STRING",
        "balance_dir_code": "STRING",
        "debt_dir_code": "STRING",
        "reset_accrual": "BOOL",
        "description": "STRING",
        "recalculate_schedule": "BOOL",
        "is_repayment": "BOOL",
        "is_repayment_reversal": "BOOL",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "last_requested_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "fee_booking": {
        "febo_id": "STRING",
        "cohe_id": "STRING",
        "coty_code": "STRING",
        "posting_date": "DATE",
        "effective_date": "DATE",
        "amt": "DECIMAL(38, 18)",
        "ccy": "STRING",
        "reversed_amt": "DECIMAL(38, 18)",
        "fee_subtype_code": "STRING",
        "source_name": "STRING",
        "source_ref": "STRING",
        "details": "STRING",
        "fee_period": "STRING",
        "updated_dtime": "TIMESTAMP",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "type_code": "STRING",
        "message_dtime": "TIMESTAMP",
    },
    "interest_condition": {
        "inco_id": "STRING",
        "cohe_id": "STRING",
        "coty_code": "STRING",
        "validity_range": "STRING",
        "rate": "DECIMAL(38, 18)",
        "calc_days_month": "STRING",
        "calc_days_year": "STRING",
        "raty_code": "STRING",
        "rate_base_code": "STRING",
        "margin_rate": "DECIMAL(38, 18)",
        "base_rate": "DECIMAL(38, 18)",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "loan_type": {
        "loty_code": "STRING",
        "reporting_banking_date": "DATE",
        "logr_code": "STRING",
        "description": "STRING",
        "amount_range": "STRING",
        "schedule_type_code": "STRING",
        "tenant_code": "STRING",
        "country_code": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
        "status_code": "STRING",
        "reporting_product_code": "STRING",
        "max_payment_free_months": "INT32",
        "scoring_valid_days": "INT32",
        "limit_usage_rule": "STRING",
        "repayment_amount_rule_code": "STRING",
        "contract_number_prefix": "STRING",
    },
    "offer": {
        "offe_id": "STRING",
        "appl_id": "STRING",
        "pers_id": "STRING",
        "loty_code": "STRING",
        "status_code": "STRING",
        "status_code_reason": "STRING",
        "requested_amt": "DECIMAL(38, 18)",
        "offered_amt": "DECIMAL(38, 18)",
        "monthly_repayment_amt": "DECIMAL(38, 18)",
        "ccy": "STRING",
        "offer_date": "DATE",
        "interest_rate": "DECIMAL(38, 18)",
        "margin_rate": "DECIMAL(38, 18)",
        "base_rate": "DECIMAL(38, 18)",
        "apr": "DECIMAL(38, 18)",
        "payment_free_months": "ARRAY<STRING>",
        "number_of_payments": "INT32",
        "loan_period": "INT32",
        "updated_dtime": "TIMESTAMP",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
        "max_invoice_amt": "DECIMAL(38, 18)",
        "min_invoice_amt": "DECIMAL(38, 18)",
        "monthly_repayment_rate": "DECIMAL(38, 18)",
    },
    "receivable": {
        "contract_id": "STRING",
        "rece_id": "STRING",
        "reporting_banking_date": "DATE",
        "receivable_type_code": "STRING",
        "receivable_number": "STRING",
        "billing_date": "DATE",
        "due_date": "DATE",
        "paid_date": "DATE",
        "status_code": "STRING",
        "ccy": "STRING",
        "amt": "DECIMAL(38, 18)",
        "net_amt": "DECIMAL(38, 18)",
        "balance_amt": "DECIMAL(38, 18)",
        "debt_amt": "DECIMAL(38, 18)",
        "tenant_code": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "receivable_event": {
        "reev_id": "STRING",
        "contract_id": "STRING",
        "reporting_banking_date": "DATE",
        "rece_id": "STRING",
        "credit_note_rece_id": "STRING",
        "reli_id": "STRING",
        "credit_note_reli_id": "STRING",
        "credited_reli_id": "STRING",
        "reversed_reev_id": "STRING",
        "cleared_reev_id": "STRING",
        "caev_id": "STRING",
        "item_type_code": "STRING",
        "receivable_event_type_code": "STRING",
        "amt_dir_code": "STRING",
        "balance_dir_code": "STRING",
        "debt_dir_code": "STRING",
        "amt": "DECIMAL(38, 18)",
        "ccy": "STRING",
        "posting_date": "DATE",
        "value_date": "DATE",
        "description": "STRING",
        "cash_source_name": "STRING",
        "cash_source_ref": "STRING",
        "target_name": "STRING",
        "target_ref": "STRING",
        "tenant_code": "STRING",
        "deli_id": "STRING",
        "payment_channel_code": "STRING",
        "updated_dtime": "TIMESTAMP",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "receivable_line": {
        "contract_id": "STRING",
        "rece_id": "STRING",
        "reli_id": "STRING",
        "reporting_banking_date": "DATE",
        "credit_note_rece_id": "STRING",
        "credited_reli_id": "STRING",
        "item_type_code": "STRING",
        "ccy": "STRING",
        "amt": "DECIMAL(38, 18)",
        "balance_amt": "DECIMAL(38, 18)",
        "debt_amt": "DECIMAL(38, 18)",
        "debt_start_date": "DATE",
        "paid_date": "DATE",
        "source_name": "STRING",
        "source_ref": "STRING",
        "tenant_code": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
    "schedule_line": {
        "scli_id": "STRING",
        "cohe_id": "STRING",
        "cove_id": "STRING",
        "reporting_banking_date": "DATE",
        "coty_code": "STRING",
        "payment_date": "DATE",
        "payment_amt": "DECIMAL(38, 18)",
        "ccy": "STRING",
        "created_by": "STRING",
        "created_dtime": "TIMESTAMP",
        "modified_by": "STRING",
        "modified_dtime": "TIMESTAMP",
        "updated_dtime": "TIMESTAMP",
        "message_dtime": "TIMESTAMP",
    },
}
