PRIMARY_KEY_MAPPING = {
    # debt domain
    "debt_contract": ["cont_id"],
    "debt_contract_debt_process_block": ["cont_id", "cdpb_id"],
    "debt_contract_notification": ["even_id"],
    "debt_contract_ready_for_collection": ["crfc_id"],
    "debt_event": ["even_id"],
    "debt_gb_indicator": ["cont_id", "indicator_value_code", "indicator_flag_code"],
    "debt_invoice": ["cont_id", "invo_id"],
    "debt_person": ["pers_id"],
    # finance domain
    "finance_account_component_rule": ["accr_id"],
    "finance_card_component_rule": ["cacr_id"],
    "finance_card_write_off_rule": ["cwor_id"],
    "finance_cost_centre_code": ["cost_centre_code"],
    "finance_deposit_component_rule": ["decr_id"],
    "finance_fin_account": ["fiac_id"],
    "finance_fin_account_balance": ["fiab_id"],
    "finance_fin_account_balance_history": ["fiabh_id"],
    "finance_fin_entry": ["id"],
    "finance_fin_entry_journal_line": ["fien_id", "joli_id"],
    "finance_fin_event": ["fiev_id"],
    "finance_fin_event_type_group": ["fetg_code", "fiet_code"],
    "finance_journal": ["jour_id"],
    "finance_journal_line": ["joli_id"],
    "finance_loan_component_rule": ["locr_id"],
    "finance_loan_write_off_rule": ["lwor_id"],
    "finance_misc_fiac_rule": ["mifr_id"],
    "finance_nostro_component_rule": ["nocr_id"],
    "finance_transit_rule": ["trru_id"],
    # loan domain
    "loan_action_history": ["achi_id"],
    "loan_application": ["appl_id"],
    "loan_borrower": ["borr_id"],
    "loan_cash": ["contract_id", "cash_id"],
    "loan_contract": ["cohe_id"],
    "loan_contract_condition": ["coco_id"],
    "loan_custom_field_value": [
        "entity_name",
        "entity_ref",
        "field_set_id",
        "field_id",
    ],
    "loan_event": ["even_id"],
    "loan_event_type": ["evty_code"],
    "loan_fee_booking": ["febo_id"],
    "loan_interest_condition": ["inco_id"],
    "loan_loan_type": ["loty_code"],
    "loan_offer": ["offe_id"],
    "loan_receivable": ["contract_id", "rece_id"],
    "loan_receivable_event": ["reev_id"],
    "loan_receivable_line": ["contract_id", "rece_id", "reli_id"],
    "loan_schedule_line": ["scli_id"],
    # person domain
    "person_address": ["addr_id"],
    "person_custom_field_value": [
        "entity_name",
        "entity_ref",
        "field_set_id",
        "field_id",
    ],
    "person_document": ["docu_id"],
    "person_financial_data": ["fida_id"],
    "person_id_number": ["idnu_id"],
    "person_person": ["pers_id"],
    "person_person_forget": ["pefo_id"],
    "person_tax_number": ["tanu_id"],
}
